import SwiftUI

/// About + privacy posture (App Store 1.0). Version, the on-device promise, and a
/// privacy-policy link — required even for a no-data app.
struct AboutView: View {
    private var version: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0"
    }
    private var build: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "1"
    }

    var body: some View {
        List {
            Section {
                VStack(spacing: DS.md) {
                    BrandIconBadge(systemName: "waveform", size: 84)
                    Text("EchoMind").font(.title2.weight(.bold))
                    Text("Private meeting memory for your iPhone")
                        .font(.subheadline).foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                    Text("Version \(version) (\(build))")
                        .font(.footnote).foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity)
                .padding(.vertical, DS.md)
                .listRowBackground(Color.clear)
            }

            Section("Your privacy") {
                privacyRow("iphone", "100% on-device", "Recordings, transcripts, and notes never leave this iPhone.")
                privacyRow("person.crop.circle.badge.xmark", "No account, no tracking", "No sign-in, no analytics, no third-party services.")
                privacyRow("sparkles", "On-device AI", "Summaries and answers are generated by Apple Intelligence, on this device.")
            }

            Section {
                Link(destination: URL(string: "https://ajace.com/echomind/privacy")!) {
                    Label("Privacy Policy", systemImage: "hand.raised.fill")
                }
                Link(destination: URL(string: "https://ajace.com/echomind/support")!) {
                    Label("Support", systemImage: "questionmark.circle.fill")
                }
            } footer: {
                Text("EchoMind collects no data. Everything you record stays on your device and can be exported or deleted at any time in Settings.")
            }
        }
        .scrollContentBackground(.hidden)
        .background(BrandBackground())
        .navigationTitle("About")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func privacyRow(_ icon: String, _ title: String, _ detail: String) -> some View {
        Label {
            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                Text(detail).font(.caption).foregroundStyle(.secondary)
            }
        } icon: {
            Image(systemName: icon).foregroundStyle(DS.brand)
        }
    }
}
